// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA7Ilhi3Nnr_1LvyYs43xai4Qs7WdjdRN8',
//     appId: '1:848798166148:web:ac462ffa109abc629226d1',
//     messagingSenderId: '848798166148',
//     projectId: 'scape-405910',
//     authDomain: 'scape-405910.firebaseapp.com',
//     storageBucket: 'scape-405910.appspot.com',
//     measurementId: 'G-VGP9L3DES8',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA9H6qENpjN-yIK9-XCnCNteWOdeEeRhiQ',
//     appId: '1:848798166148:android:9fdfb43f4dabd8159226d1',
//     messagingSenderId: '848798166148',
//     projectId: 'scape-405910',
//     storageBucket: 'scape-405910.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB9tZf_o5eZEfKbzQnF-B9f5w1gEELNqsk',
//     appId: '1:848798166148:ios:93041fbabf2892839226d1',
//     messagingSenderId: '848798166148',
//     projectId: 'scape-405910',
//     storageBucket: 'scape-405910.appspot.com',
//     androidClientId: '848798166148-orai04hmq2kkijpe5h5pmegbk6rek97f.apps.googleusercontent.com',
//     iosClientId: '848798166148-c5uet2g51eg5u4l3ihc8u2l5jv67pqno.apps.googleusercontent.com',
//     iosBundleId: 'com.security.scape',
//   );
// }
